name: Docker-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 00:00 UTC on the 1, 6, 11, 16, 21, 26 and 31th of every month
  schedule:
    - cron:  '0 0 */5 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone
        shell: bash
        run: git clone ${{ secrets.DOCKERHUB_USERNAME }}
